//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CafeCMUhuhu.Module.BusinessObjects.ORMDataModel1
{

    [DefaultProperty("SoBan")]
    public partial class Ban : DevExpress.Persistent.BaseImpl.BaseObject
    {
        int fSoBan;
        public int SoBan
        {
            get { return fSoBan; }
            set { SetPropertyValue<int>(nameof(SoBan), ref fSoBan, value); }
        }
        string fThuocTinh;
        public string ThuocTinh
        {
            get { return fThuocTinh; }
            set { SetPropertyValue<string>(nameof(ThuocTinh), ref fThuocTinh, value); }
        }
        [Association(@"HoaDonReferencesBan")]
        public XPCollection<HoaDon> HoaDons { get { return GetCollection<HoaDon>(nameof(HoaDons)); } }
    }

}
