//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CafeCMUhuhu.Module.BusinessObjects.ORMDataModel1
{

    public partial class BangLuong : DevExpress.Persistent.BaseImpl.BaseObject
    {
        NhanVien fNhanVien_ID;
        [Association(@"BangLuongReferencesNhanVien")]
        public NhanVien NhanVien_ID
        {
            get { return fNhanVien_ID; }
            set { SetPropertyValue<NhanVien>(nameof(NhanVien_ID), ref fNhanVien_ID, value); }
        }
        string fNam;
        public string Nam
        {
            get { return fNam; }
            set { SetPropertyValue<string>(nameof(Nam), ref fNam, value); }
        }
        string fThang;
        public string Thang
        {
            get { return fThang; }
            set { SetPropertyValue<string>(nameof(Thang), ref fThang, value); }
        }
        int fSoGio;
        public int SoGio
        {
            get { return fSoGio; }
            set { SetPropertyValue<int>(nameof(SoGio), ref fSoGio, value); }
        }
        [PersistentAlias("[SoGio] * 25000")]
        public decimal Luong
        {
            get { return (decimal)(EvaluateAlias(nameof(Luong))); }
        }
    }

}
