//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CafeCMUhuhu.Module.BusinessObjects.ORMDataModel1
{

    [DefaultProperty("NhaCungCap")]
    public partial class DongNhap : DevExpress.Persistent.BaseImpl.BaseObject
    {
        SanPham fSanPham_ID;
        [Association(@"DongNhapReferencesSanPham")]
        public SanPham SanPham_ID
        {
            get { return fSanPham_ID; }
            set { SetPropertyValue<SanPham>(nameof(SanPham_ID), ref fSanPham_ID, value); }
        }
        PhieuNhap fNhap_ID;
        [Association(@"DongNhapReferencesPhieuNhap")]
        public PhieuNhap Nhap_ID
        {
            get { return fNhap_ID; }
            set { SetPropertyValue<PhieuNhap>(nameof(Nhap_ID), ref fNhap_ID, value); }
        }
        int fSoLuong;
        public int SoLuong
        {
            get { return fSoLuong; }
            set { SetPropertyValue<int>(nameof(SoLuong), ref fSoLuong, value); }
        }
        decimal fGia;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###")]
[DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ### ###")]
        public decimal Gia
        {
            get { return fGia; }
            set { SetPropertyValue<decimal>(nameof(Gia), ref fGia, value); }
        }
    }

}
