//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CafeCMUhuhu.Module.BusinessObjects.ORMDataModel1
{

    [DefaultProperty("HoTen")]
    public partial class NhanVien : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fHoTen;
        public string HoTen
        {
            get { return fHoTen; }
            set { SetPropertyValue<string>(nameof(HoTen), ref fHoTen, value); }
        }
        string fSoDienThoai;
        public string SoDienThoai
        {
            get { return fSoDienThoai; }
            set { SetPropertyValue<string>(nameof(SoDienThoai), ref fSoDienThoai, value); }
        }
        decimal fLuongTheoGio;
        public decimal LuongTheoGio
        {
            get { return fLuongTheoGio; }
            set { SetPropertyValue<decimal>(nameof(LuongTheoGio), ref fLuongTheoGio, value); }
        }
        [Association(@"PhieuNhapReferencesNhanVien")]
        public XPCollection<PhieuNhap> PhieuNhaps { get { return GetCollection<PhieuNhap>(nameof(PhieuNhaps)); } }
        [Association(@"BangLuongReferencesNhanVien")]
        public XPCollection<BangLuong> BangLuongs { get { return GetCollection<BangLuong>(nameof(BangLuongs)); } }
        [Association(@"PhieuChiReferencesNhanVien")]
        public XPCollection<PhieuChi> PhieuChis { get { return GetCollection<PhieuChi>(nameof(PhieuChis)); } }
    }

}
