//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CafeCMUhuhu.Module.BusinessObjects.ORMDataModel1
{

    public partial class HoaDon : DevExpress.Persistent.BaseImpl.BaseObject
    {
        SanPham fSanPham_ID;
        public SanPham SanPham_ID
        {
            get { return fSanPham_ID; }
            set { SetPropertyValue<SanPham>(nameof(SanPham_ID), ref fSanPham_ID, value); }
        }
        NhanVien fNhanVien_ID;
        public NhanVien NhanVien_ID
        {
            get { return fNhanVien_ID; }
            set { SetPropertyValue<NhanVien>(nameof(NhanVien_ID), ref fNhanVien_ID, value); }
        }
        Ban fSoBan_ID;
        [Association(@"HoaDonReferencesBan")]
        public Ban SoBan_ID
        {
            get { return fSoBan_ID; }
            set { SetPropertyValue<Ban>(nameof(SoBan_ID), ref fSoBan_ID, value); }
        }
        KhachHang fKhachHang_ID;
        [Association(@"HoaDonReferencesKhachHang")]
        public KhachHang KhachHang_ID
        {
            get { return fKhachHang_ID; }
            set { SetPropertyValue<KhachHang>(nameof(KhachHang_ID), ref fKhachHang_ID, value); }
        }
        int fSoLuong;
        public int SoLuong
        {
            get { return fSoLuong; }
            set { SetPropertyValue<int>(nameof(SoLuong), ref fSoLuong, value); }
        }
        DateTime fNgay;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm")] [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime Ngay
        {
            get { return fNgay; }
            set { SetPropertyValue<DateTime>(nameof(Ngay), ref fNgay, value); }
        }
        decimal fDongGia;
        public decimal DongGia
        {
            get { return fDongGia; }
            set { SetPropertyValue<decimal>(nameof(DongGia), ref fDongGia, value); }
        }
        decimal fChiPhiKhac;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###")]
[DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ### ###")]
        public decimal ChiPhiKhac
        {
            get { return fChiPhiKhac; }
            set { SetPropertyValue<decimal>(nameof(ChiPhiKhac), ref fChiPhiKhac, value); }
        }
        [PersistentAlias("ToDecimal([SoLuong]) * [DongGia] - [ChiPhiKhac]")]
        public decimal ThanhGia
        {
            get { return (decimal)(EvaluateAlias(nameof(ThanhGia))); }
        }
        [Association(@"TieuHaoReferencesHoaDon")]
        public XPCollection<TieuHao> TieuHaos { get { return GetCollection<TieuHao>(nameof(TieuHaos)); } }
    }

}
