//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CafeCMUhuhu.Module.BusinessObjects.ORMDataModel1
{

    [DefaultProperty("HoTen")]
    public partial class NhaCungCap : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fHoTen;
        public string HoTen
        {
            get { return fHoTen; }
            set { SetPropertyValue<string>(nameof(HoTen), ref fHoTen, value); }
        }
        string fDienThoai;
        public string DienThoai
        {
            get { return fDienThoai; }
            set { SetPropertyValue<string>(nameof(DienThoai), ref fDienThoai, value); }
        }
        string fMST;
        public string MST
        {
            get { return fMST; }
            set { SetPropertyValue<string>(nameof(MST), ref fMST, value); }
        }
        [Association(@"PhieuNhapReferencesNhaCungCap")]
        public XPCollection<PhieuNhap> PhieuNhaps { get { return GetCollection<PhieuNhap>(nameof(PhieuNhaps)); } }
        [Association(@"PhieuChiReferencesNhaCungCap")]
        public XPCollection<PhieuChi> PhieuChis { get { return GetCollection<PhieuChi>(nameof(PhieuChis)); } }
    }

}
