//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CafeCMUhuhu.Module.BusinessObjects.ORMDataModel1
{

    public partial class PhieuChi : DevExpress.Persistent.BaseImpl.BaseObject
    {
        NhanVien fNhanVien_ID;
        [Association(@"PhieuChiReferencesNhanVien")]
        public NhanVien NhanVien_ID
        {
            get { return fNhanVien_ID; }
            set { SetPropertyValue<NhanVien>(nameof(NhanVien_ID), ref fNhanVien_ID, value); }
        }
        NhaCungCap fNhaCungCap_ID;
        [Association(@"PhieuChiReferencesNhaCungCap")]
        public NhaCungCap NhaCungCap_ID
        {
            get { return fNhaCungCap_ID; }
            set { SetPropertyValue<NhaCungCap>(nameof(NhaCungCap_ID), ref fNhaCungCap_ID, value); }
        }
        int fSo;
        public int So
        {
            get { return fSo; }
            set { SetPropertyValue<int>(nameof(So), ref fSo, value); }
        }
        string fNgay;
        public string Ngay
        {
            get { return fNgay; }
            set { SetPropertyValue<string>(nameof(Ngay), ref fNgay, value); }
        }
        string fTen;
        public string Ten
        {
            get { return fTen; }
            set { SetPropertyValue<string>(nameof(Ten), ref fTen, value); }
        }
    }

}
