//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CafeCMUhuhu.Module.BusinessObjects.ORMDataModel1
{

    public partial class SanPham : DevExpress.Persistent.BaseImpl.BaseObject
    {
        LoaiHang fLoaiHang;
        [Association(@"SanPhamReferencesLoaiHang")]
        public LoaiHang LoaiHang
        {
            get { return fLoaiHang; }
            set { SetPropertyValue<LoaiHang>(nameof(LoaiHang), ref fLoaiHang, value); }
        }
        string fTenSp;
        public string TenSp
        {
            get { return fTenSp; }
            set { SetPropertyValue<string>(nameof(TenSp), ref fTenSp, value); }
        }
        string fDvt;
        public string Dvt
        {
            get { return fDvt; }
            set { SetPropertyValue<string>(nameof(Dvt), ref fDvt, value); }
        }
        decimal fGiaBan;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###")]
[DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ### ###")]
        public decimal GiaBan
        {
            get { return fGiaBan; }
            set { SetPropertyValue<decimal>(nameof(GiaBan), ref fGiaBan, value); }
        }
        [Association(@"DongNhapReferencesSanPham")]
        public XPCollection<DongNhap> DongNhaps { get { return GetCollection<DongNhap>(nameof(DongNhaps)); } }
        [Association(@"DinhLuongReferencesSanPham")]
        public XPCollection<DinhLuong> DinhLuongs { get { return GetCollection<DinhLuong>(nameof(DinhLuongs)); } }
        [Association(@"TieuHaoReferencesSanPham")]
        public XPCollection<TieuHao> TieuHaos { get { return GetCollection<TieuHao>(nameof(TieuHaos)); } }
    }

}
